#[derive(Clone, Copy, Debug, Primitive, PartialEq, Eq, Hash)]
pub enum TStyleId {
	Default = 0,
	Title = 1,
	Subtitle = 2,
	Composer = 3,
	Poet = 4,
	LyricsOdd = 5,
	LyricsEven = 6,
	Fingering = 7,
	LhGuitarFingering = 8,
	RhGuitarFingering = 9,
	StringNumber = 10,
	InstrumentLong = 11,
	InstrumentShort = 12,
	InstrumentExcerpt = 13,
	Dynamics = 14,
	Expression = 15,
	Tempo = 16,
	Metronome = 17,
	MeasureNumber = 18,
	Translator = 19,
	Tuplet = 20,
	System = 21,
	Staff = 22,
	HarmonyA = 23,
	HarmonyB = 24,
	HarmonyRoman = 25,
	HarmonyNashville = 26,
	RehearsalMark = 27,
	/// align to start of measure
	RepeatLeft = 28,
	/// align to end of measure
	RepeatRight = 29,
	Frame = 30,
	Textline = 31,
	Glissando = 32,
	Ottava = 33,
	Volta = 34,
	Pedal = 35,
	LetRing = 36,
	PalmMute = 37,
	Hairpin = 38,
	Bend = 39,
	Header = 40,
	Footer = 41,
	InstrumentChange = 42,
	Sticking = 43,
	User1 = 44,
	User2 = 45,
	User3 = 46,
	User4 = 47,
	User5 = 48,
	User6 = 49,
	/// special, no-contents, styles used while importing older scores
	/// used for user-defined styles
	TextStyles = 50,
	/// used for styles no longer relevant (mainly Figured bass text style)
	IgnoredStyles = 51,
}
